### ISSUE TITLE
Include a Table of Contents in the readme

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/sample-source#119]
We should call out the constituent elements of this repo that we expect a "complete" source to implement.  This currently includes the types and controller structure, but we should also include:

docs: https://github.com/knative-sandbox/sample-source/issues/118
cli plugin: https://github.com/knative-sandbox/sample-source/issues/117

... and anything else we might expect folks building a source to implement.

cc @lionelvillard @evankanderson @n3wscott @vaikas @nachocano

**Comment by vaikas** [comment]
I think there's probably something about observability, say things like tracing information and so forth.

**Comment by mattmoor** [comment]
Conformance testing: https://github.com/knative-sandbox/sample-source/issues/120

**Comment by lionelvillard** [comment]
pinging @lberk as he's been looking at this in the past.
