### ISSUE TITLE
Use of `pkgreconciler.Event` produces false-positive error messages

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/sample-source#359]
From my understanding, using `pkgreconciler.Event` to bubble up `errors` to the reconciler factory during reconciliation is encouraged when building `sources` (hence heavily used in the `sample-source`).

This is generally fine [1], but produces false-positive errors during resource updates. This is triggered in this line:

https://github.com/knative-sandbox/sample-source/blob/70e16ec9d1a6766d00d593186662f1ed686692d0/pkg/reconciler/sample/samplesource.go#L78-L81

"Caused" by:

```go
// newDeploymentUpdated makes a new reconciler event with event type Normal, and
// reason DeploymentUpdated.
func newDeploymentUpdated(namespace, name string) pkgreconciler.Event {
	return pkgreconciler.NewEvent(corev1.EventTypeNormal, "DeploymentUpdated", "updated deployment: \"%s/%s\"", namespace, name)
}
```

Ideally, such events should be recorded, but not expressed as errors. Thoughts? cc/ @n3wscott @mattmoor 

I understand that this might be a more fundamental question (issue) in `knative.dev/pkg/reconciler`, but wanted to bring it up here first since it shows the behavior of the pattern.

[1]
Though I'd welcome a signature change to return `error` instead of `pkgreconciler.Event` :) (happy to file a PR if that makes sense)

**Comment by mattmoor** [comment]
Ack, it is super weird that we used a wrapped error type for this, and I never personally use it, but I don't think it is worth a breaking signature change to fix.

> but produces false-positive errors during resource updates

I'm curious how this is manifesting for you in a problematic way?

**Comment by mattmoor** [comment]
Yeah, I think that could definitely be better.

**Comment by embano1** [comment]
Would you consider this a reasonable fix in the `sample-source`?

```go
func (r *Reconciler) ReconcileKind(ctx context.Context, src *v1alpha1.HorizonSource) pkgreconciler.Event {
    // reconcile stuff

	// ignore normal reconcile events
	var reconcileErr *pkgreconciler.ReconcilerEvent
	if errors.As(err, &reconcileErr) {
		if reconcileErr.EventType == corev1.EventTypeNormal {
			return nil
		}
	}

	if err != nil {
		logging.FromContext(ctx).Errorw("returning because of non-normal event from ReconcileDeployment", zap.Error(err))
		return err
	}

	return nil
```
